### ISSUE TITLE
Scope the trustrelationship to an AWS Account instead of oidc-provider

### ISSUE THREAD

**Issue by janwillies** [aws/amazon-eks-pod-identity-webhook#101]
**What would you like to be added**:
Today the trustrelationship for IRSA needs a specific eks cluster (respective oidc-provider). Within the `Condition` the oidc-provider is referenced and  a `Namespace` and optionally a `ServiceAccount` has to be specified: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#iam-role-configuration

I'd like to be able to specify an AWS Account as the trustrelationship. I tried using the AWS Account ID as the `Principal` with some variations of `StringLike` conditions, but wasn't able to get it working

**Why is this needed**:
I'd like to implement namespace-sameness: https://github.com/kubernetes/community/blob/master/sig-multicluster/namespace-sameness-position-statement.md
While this is possible with IRSA, it is a lot of work.

**Comment by micahhausler** [comment]
> I'd like to be able to specify an AWS Account as the trustrelationship. I tried using the AWS Account ID as the Principal with some variations of StringLike conditions, but wasn't able to get it working

Do you mean you want all EKS clusters in a given AWS account to be able to issue tokens that can assume the same IAM role?

**Comment by janwillies** [comment]
Yes. Specifically a certain namespace in all EKS Clusters in a given AWS account to assume the same IAM role

**Comment by micahhausler** [comment]
Gotcha, that would be new functionality for IAM and probably EKS as well. I'd looking over the open issues in the [aws/containers-roadmap](https://github.com/aws/containers-roadmap/issues?q=is%3Aissue+is%3Aopen+iam+role+label%3AEKS+) repo, and if there isn't something quite like your request, open an issue there.
