### ISSUE TITLE
[question] it looks like a user can pick their role, is this secure?

### ISSUE THREAD

**Issue by raffaelespazzoli** [aws/amazon-eks-pod-identity-webhook#104]
This is just a question from a new user. 
If I understand correctly, the final ARN role that the generated token will have is decided by the service account annotation: `eks.amazonaws.com/role-arn`.
Now normally tenants of a Kubernetes clusters are allowed to edit their service accounts, so here one can put anything they want.
How does this makes the approach secure? What is stopping a tenant from picking a role they shouldn't have? For example a role that was intended for another tenant of the same cluster?

**Comment by micahhausler** [comment]
The annotation role ARN essentially only tells the AWS SDK in your pod which role ARN to use in the `sts:AssumeRoleWithWebIdentity` API call. The real trust comes from [configuring the IAM Role's Trust Policy](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#iam-role-configuration) to a specific cluster and specific service account

**Comment by micahhausler** [comment]
Closing with no response
