### ISSUE TITLE
eks.amazonaws.com/token-expiration service account annotation ignored

### ISSUE THREAD

**Issue by rittneje** [aws/amazon-eks-pod-identity-webhook#105]
As per the README, I attempted to set the `eks.amazonaws.com/token-expiration` annotation on the service account to a value other than `"86400"`. However, no matter what I do, this annotation is completely ignored, and the `expirationSeconds` of the projected volume in the pod is always `86400`. Is there a minimum required EKS version? We are currently using Kubernetes 1.15.

**Comment by sidewinder12s** [comment]
Looks like EKS requires 1.19: https://github.com/aws/containers-roadmap/issues/1274
