### ISSUE TITLE
data does not contain any valid RSA or ECDSA public keys

### ISSUE THREAD

**Issue by hatappi** [aws/amazon-eks-pod-identity-webhook#11]
**What happened**:
tried [SELF_HOSTED_SETUP](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md) on my kubernetes cluster.
this cluster is made by [kops](https://github.com/kubernetes/kops).

I specified in `kube-apiserver --service-accuont-key-file sa-signer.key.pub` using the public key I created.
But error is occured.

```sh
error: invalid authentication config: error reading public key file /sa-signer.key.pub: data does not contain any valid RSA or ECDSA public keys
```

**What you expected to happen**:
Generate a public key with the correct format and start kube-apiserver

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a public key according to [the document](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#projected-token-signing-keypair)
2. `kube-apiserver --service-accuont-key-file $PUB_KEY` 

**Anything else we need to know?**:
none

**Environment**:
- AWS Region:ap-northeast-1
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`):not use EKS
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`):v1.15.3
- Webhook Version:master `4de06cb9837034e688758638250934ce2aff97f0`

**Comment by micahhausler** [comment]
It looks like you're misspelling `--service-accuont-key-file`, it should be `--service-accuont-key-file`

Also, you probably want to give the absolute path of the key file, it looks like the API server is looking for `/sa-signer.key.pub`

**Comment by hatappi** [comment]
sorry to confuse you.
The same error occured even if specify an absolute path

**Comment by Jacobious52** [comment]
Hi, I ran into this problem as well. I solved it by using the coverted `sa-signer-pkcs8.pub` instead of `sa-signer.key.pub`.

There is an error in the [self setup](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md) guide regarding which key to use for `--service-account-key-file` 

Where it says:
``` 
# This flag is likely already specified for legacy service accounts, you can
# specify this flag multiple times, and you'll need to add this with the path
# to the $PUB_KEY file from the beginning
```

`$PUB_KEY` should be `$PKCS_KEY`, as $PKCS_KEY is the the format the api-server recognises.

**Comment by hatappi** [comment]
@Jacobious52 
Thank you for comment.
I tried using `$PKCS_KEY` instead of `$PUB_KEY`.
And apiserver has started 👍

**Comment by smalltown** [comment]
I also encounter the same issue, using `$PKCS_KEY` should fix the problem. 

And according to the [official api server document](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/), 
the file need to contain ` PEM-encoded x509 RSA or ECDSA` keys, 
hence, it's expected to encounter exception when following the original tutorial
