### ISSUE TITLE
eks.amazonaws.com/sts-regional-endpoints has no effect

### ISSUE THREAD

**Issue by arunvelsriram** [aws/amazon-eks-pod-identity-webhook#110]
**What happened**:

`eks.amazonaws.com/sts-regional-endpoints: "true"` annotation is not injecting `AWS_STS_REGIONAL_ENDPOINTS=regional` to the Pods.

**What you expected to happen**:

`AWS_STS_REGIONAL_ENDPOINTS=regional` is injected in to the Pods.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a serviceaccount as mentioned in the README with annotation `eks.amazonaws.com/sts-regional-endpoints: "true"`
2. Create a Pod, using that serviceaccount

**Anything else we need to know?**:

I noticed that in the README there are two versions of the annotation:

- `eks.amazonaws.com/sts-regional-endpoints: "true"` - https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/README.md#eks-walkthrough
- `eks.amazonaws.com/sts-regional-endpoint: "true"` - https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/README.md#aws_sts_regional_endpoints-injection

Which one is correct?

**Environment**:
- AWS Region: ap-south-1
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.1
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`): 1.19
- Webhook Version: Am using AWS EKS, so not sure how to find the version

**Comment by nicoaws** [comment]
any ETA for the resolution of this?

**Comment by edify42** [comment]
I think I've found where [the issue in line 202 here](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/ed8c41fcc820e2ec84ec2a7faff879eab4db65d3/pkg/handler/handler.go#L202) with the if statement evaluating to **false**.

`m.RegionalSTSEndpoint` [is set in main.go as a flag](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/main.go#L67) and unless you set this to true on the webhook it won't add the regional endpoint ENV var - this conflicts with the README.md doc which states that:
```
You can also enable this per-service account with the annotation eks.amazonaws.com/sts-regional-endpoint set to "true".
```

**Comment by jyotimahapatra** [comment]
https://github.com/aws/amazon-eks-pod-identity-webhook/pull/117
