### ISSUE TITLE
admissionregistration.k8s.io/v1beta1 was deprecated in 1.22

### ISSUE THREAD

**Issue by ss098** [aws/amazon-eks-pod-identity-webhook#132]
**What happened**:

`admissionregistration.k8s.io/v1beta1` api removed in kubernetes 1.22.

**What you expected to happen**:

[https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/deploy/mutatingwebhook.yaml#L1](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/deploy/mutatingwebhook.yaml#L1)

Migrate admissionregistration from `v1beta1` to `v1`.

**Comment by h3poteto** [comment]
I think we need to merge #115 at first.

**Comment by LauraCameran** [comment]
I think this issue can be closed since commit https://github.com/aws/amazon-eks-pod-identity-webhook/commit/d3d1b4cbc58e7ad25155e73778c8f80ffc6668c5
