### ISSUE TITLE
EKS Pod Identity is not working when holdApplicationUntilProxyStarts is enabled

### ISSUE THREAD

**Issue by abebars** [aws/amazon-eks-pod-identity-webhook#159]
**What happened**:
When (ISTIO) holdApplicationUntilProxyStarts is set to true we notice that containers can't start, and the replica controller is erroring out reading the Service Token
``` 
│ ntainers[0].volumeMounts[2].mountPath: Invalid value: "/var/run/secrets/eks.amazonaws.com/serviceaccount": must be unique]
```
**What you expected to happen**:
Pod should be created and inject with Token as expected
**How to reproduce it (as minimally and precisely as possible)**:
Deployment with Istio Inject with and holdApplicationUntilProxyStarts set to true will cause 
 
**Anything else we need to know?**:

**Environment**:
- AWS Region: us-east-1
- EKS Platform version: eks.5
- Kubernetes version 1.22
- Webhook Version:

Ref: https://github.com/istio/istio/issues/40993

**Comment by TaihengJin** [comment]
@abebars We're seeing the same error as yours, wondering how did you work around the issue? thanks

**Comment by TaihengJin** [comment]
EKS Platform version: eks.4
Kubernetes version 1.28

**Comment by infa-ddeore** [comment]
we have same issue for some k8 pods only, any known fix for this available?
