### ISSUE TITLE
New release v0.5.0?

### ISSUE THREAD

**Issue by njuettner** [aws/amazon-eks-pod-identity-webhook#188]
Any plans for a new release? I would be really happy to see a release of the `compose role arn` feature 🙂.

**Comment by james-callahan** [comment]
0.5.0 was released.

**Comment by danielloader** [comment]
How does one know when it actually gets added to an eks cluster?

**Comment by prateekgogia** [comment]
Current release version is at 0.5.2.
> How does one know when it actually gets added to an eks cluster?

Once a release tag is cut in this repo, its gets rolled out to all EKS cluster across all regions in few weeks.

**Comment by prateekgogia** [comment]
Marking this issue as closed, feel free to reopen if there are any pending questions/issues.
