### ISSUE TITLE
SELF_HOSTED_SETUP: What if service-account-* options already set?

### ISSUE THREAD

**Issue by mimmus** [aws/amazon-eks-pod-identity-webhook#197]
Hi,
I'm trying to understand if I can install IRSA on a self-hosted Kubernetes cluster.
Looking at my `kube-apsiserver` pods, I see that following flags:
```
        - '--service-account-issuer=https://kubernetes.default.svc.cluster.local'
        - '--service-account-key-file=/etc/kubernetes/pki/sa.pub'
        - '--service-account-signing-key-file=/etc/kubernetes/pki/sa.key'
```
are already set.
What are the possibilities of installing IRSA?

**Comment by prateekgogia** [comment]
Please can follow this guide and let us know if this doesn't help - https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md

**Comment by mimmus** [comment]
Guide suggest to set:
```
--service-account-key-file
--service-account-signing-key-file
--service-account-issuer

```but these are already set in my cluster.

**Comment by prateekgogia** [comment]
Have you followed the other steps like `S3 bucket creation, Create the OIDC discovery and keys documents, Provider creation and Deploying the webhook`? 
Whats the error you are seeing?

**Comment by mimmus** [comment]
No, I’m still evaluating all steps.
In particular, I’m wondering how I can safely add these options to an existing cluster having these already set, for another OIDC provider (Dex).

Thanks again

**Comment by et304383** [comment]
I have the same questions. Like, anyone trying to add this to an existing cluster is going to have the same questions yet the doc completely glosses over this.

If I change the value for issuer I get the same bearer errors from #126 .
