### ISSUE TITLE
Want to pull an image from ECR to a general kubernetes cluster using AWS Identity Federation

### ISSUE THREAD

**Issue by mist714** [aws/amazon-eks-pod-identity-webhook#201]
**What would you like to be added**:
Is there a function to dynamically create a token as a secret using identity federation and specify it as an image pull secret for a service account?

**Why is this needed**:
We plan to use it to pull ECR images from general k8s clusters other than eks.

**Comment by jwthanh** [comment]
Hi @mist714, Have you found the solution for this?

**Comment by mist714** [comment]
Yes, https://github.com/pfnet/image-pull-secrets-provisioner enables this.
