### ISSUE TITLE
Have the OIDC provider provide OIDC compliant claims

### ISSUE THREAD

**Issue by mutiger86** [aws/amazon-eks-pod-identity-webhook#21]
**What would you like to be added**:

Currently, the subject claim passed by the OIDC provider is a very long string mentioning the region, account, cluster, etc. (e.g., oidc.\<region\>.amazonaws.com/id/oidc.eks.\<region\>.amazonaws.com/id/\<IDENTIFIER\>:sub)  This is very much in the form of a SAML claim, not an OIDC claim, and is not compliant with OIDC spec (https://openid.net/specs/openid-connect-core-1_0.html#IDToken).

**Why is this needed**:

This should be fixed to be compliant with the OIDC spec, but also it should be fixed because it makes writing trust relationship policies more difficult.  For instance, if you want a role to be assumable by a service account running on any cluster, you have to have multiple condition lines.  If the claim was simply passed as "sub" claim (as OIDC specifies), it could be a single condition.

**Comment by micahhausler** [comment]
Thanks for this issue. If you take a projected Service Account token and decode it with something like [jwtdecode](https://github.com/micahhausler/jwtdecode), you'll see the following in the payload section of the jwt:

```json
{
  "aud": [
    "sts.amazonaws.com"
  ],
  "exp": 1576225918,
  "iat": 1576139518,
  "iss": "https://oidc.eks.us-east-2.amazonaws.com/id/5E5D7BAA84911ACC36EE4D978F209DD7",
  "kubernetes.io": {
    "namespace": "default",
    "pod": {
      "name": "sleeper-6b76c4f5dc-h4twj",
      "uid": "b6d0594c-1b77-11ea-9b61-065c2ccc07e2"
    },
    "serviceaccount": {
      "name": "default",
      "uid": "6b45e39d-10a3-11ea-9b61-065c2ccc07e2"
    }
  },
  "nbf": 1576139518,
  "sub": "system:serviceaccount:default:default"
}
```

Kubernetes is minting a OIDC valid token with a proper [subject claim](https://github.com/kubernetes/kubernetes/blob/master/pkg/serviceaccount/claims.go#L53-L57), but it is the IAM policy grammar, and specifically the [condition keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#condition-keys-wif) that require the verbose key specification.

If you would like that syntax changed, you'd probably need to take that issue up with IAM

**Comment by mutiger86** [comment]
Thank you for the clarification.  I was going by the IAM rule and not the actual token.  I will therefore close this issue.

**Comment by yanilov** [comment]
@mutiger86, Did you find a workaround for the trust policy syntax issue? is there a trick to add a condition on the subject claim without specifying all EKS cluster?
