### ISSUE TITLE
Live refresh of pod credentials after PIA is created

### ISSUE THREAD

**Issue by vitorguidi** [aws/amazon-eks-pod-identity-webhook#210]
**What would you like to be added**:

Currently, pod identity association env vars are only injected at the moment of pod creation. We would like the credentials to be refreshed if the pod identity association is created within the cluster.

**Why is this needed**:

We want to create pod identity associations automatically through an inhouse controller, but due to bad timing, we might have the sequence of events:

- Pod is created
- AWS admission webhook runs and injects PIA credentials. As there is still no association for current cluster/SA/namespace, the PIA credentials are not injected
- Custom inhouse controller creates association through AWS API
- Pod does not notice the update, perms do not get refreshed
- Pod unable to assume role

A workaround is to `k rollout restart` the deployment, through the controller after the PIA creation, forcing new pods to be deployed with fresh perms. However, this is risky, as lightly restarting production deployments is not desirable. Thus, a way for the refresh of credentials AFTER a PIA is created, would be really useful.

**Comment by jackkleeman** [comment]
I don't think its possible, because you can't update the volumes or environment variables of the pod after its already created. The pod would have to be recreated

**Comment by vitorguidi** [comment]
We worked around this by adding an annotation to the deployment, signaling the association was created on the AWS side and forcing a deployment restart and recreation of the pods.
