### ISSUE TITLE
Cross account assume role request

### ISSUE THREAD

**Issue by mustafaakin** [aws/amazon-eks-pod-identity-webhook#24]
**What would you like to be added**:

I would like to assume roles in a foreign account as long as they allow.

**Why is this needed**:

kiam & kube2iam supports it, but when I tried it using the proper assume role policies, it give the error that it could not find the OIDC provider in the account.

**Comment by micahhausler** [comment]
This is fully supported in EKS and on your self-managed cluster. There are two ways to do this: by first assuming a role in the same account and then assuming a cross account role, or by creating an OIDC provider using the cluster's endpoint in IAM in the second account and directly assuming the role. They're both outlined in the [EKS docs](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#cross-account-access) 

Does that suit your use case?

**Comment by mustafaakin** [comment]
Creating an OIDC provider in the second account worked nicer, sorry somehow I missed that in the docs even though looking throughly, but apparently not enough. Thanks!
