### ISSUE TITLE
Service account in on-premise cluster

### ISSUE THREAD

**Issue by Swalloow** [aws/amazon-eks-pod-identity-webhook#25]
**What would you like to be added**:

We have EKS cluster in VPC, Kubernetes cluster in On-Premise.
The two clusters are connected by AWS direct connect.
Can we install eks-pod-identity-webhook into the On-Premise cluster?
We needed to use IAM Role-based Auth in both clusters.
Thanks!

**Comment by micahhausler** [comment]
You sure can, see the [SELF_HOSTED_SETUP](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md) guide.

Does that solve your use case?

**Comment by Swalloow** [comment]
@micahhausler Thank you for the guide. I will close the issue.
