### ISSUE TITLE
Ability to lock down access to the OIDC discovery endpoint

### ISSUE THREAD

**Issue by johnmccabe** [aws/amazon-eks-pod-identity-webhook#27]
**What would you like to be added**:

Rather than making the OIDC discovery endpoint completely public for the self hosted case might there be a mechanism which would allow it to be locked down to requests originating from STS only, or at least cut down on sources from which it would be accessible.

**Why is this needed**:

It would be desirable to not leak any information at all about internal implementations.

**Comment by micahhausler** [comment]
STS only needs the _public_ signing key and OIDC discovery endpoint to be public. There doesn't need to be any private information present, what information are you concerned about exposing?

**Comment by johnmccabe** [comment]
hi @micahhausler, I appreciate that no secrets are exposed here, I was hoping however that we might have a mechanism where we can avoid unnecessary information disclosure. The keys/discovery metadata are only being accessed by STS (right?) so restricting access to that is preferable to being completely public. (We wouldn't necessarily want to make public our decisions around architecture unless there are no alternatives)

**Comment by micahhausler** [comment]
> here, I was hoping however that we might have a mechanism where we can avoid unnecessary information disclosure

I'm still not sure I understand, what specific information are you referring to that you don't want to be public? In EKS the public endpoint only contains public RSA keys (ex: [discovery](https://oidc.eks.us-west-2.amazonaws.com/id/4B722CC71565F461A41AE9899D8D92C4/.well-known/openid-configuration) and [keys ](https://oidc.eks.us-west-2.amazonaws.com/id/4B722CC71565F461A41AE9899D8D92C4/keys)). There isn't any identifying information required by STS.  Is there a particular vector in your threat model that isn't described here?

> The keys/discovery metadata are only being accessed by STS (right?) so restricting access to that is preferable to being completely public. 

STS doesn't have a set list of egress IPs they access from, so there isn't a way to restrict the access like you're wanting. If this is something you specifically need, you'd have to take that up with IAM/STS, the best way to communicate that would be through your account rep.

**Comment by johnmccabe** [comment]
> Is there a particular vector in your threat model that isn't described here?

I wanted to be able to address the rationale for exposing discovery/keys in a public bucket.

> you'd have to take that up with IAM/STS, the best way to communicate that would be through your account rep

I'll chase it there.

Closing this ticket, thanks for the input.
