### ISSUE TITLE
Should updates to service accounts trigger pod changes?

### ISSUE THREAD

**Issue by errordeveloper** [aws/amazon-eks-pod-identity-webhook#28]
This is rather a question, not a feature request as such.

As far as I understand the implementation, at the moment if one alters the role ARN in the service account annotation, either by changing the ARN itself to a different role or unsetting it, nothing will happen until a new pod gets created.

The question is: assuming current default behaviour (at least in EKS) should remain as is,  should there be alternative behaviour where pods get affected in event of role ARN changes?

**Comment by micahhausler** [comment]
Currently, it is up to the operator to cycle out the pods using a previous IAM role if you changed the role annotation on the Service Account. This is helpful if you want to do a migration, since multiple IAM roles can be whitelisted to use the same Service Account, the old pods will continue to use the old role. Additionally, environment variables cannot be live updated in an existing pod.

One way I can think of to trigger pod changes when the role annotation changes would be using a trick that Helm uses, where you have an annotation on your pod that is a hash of the IAM role. (See [helm docs](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments))

**Comment by errordeveloper** [comment]
Thanks for clarifying the benefits of current behaviour, that is already helpful to anyone stumbling upon this! I am not anything has to be done, just thought I'd raise this as I realised how things work.

**Comment by errordeveloper** [comment]
I guess it would important to document what is the point of control. Clearly service account annotations provide only partial control, and to the user it may see that they are the ultimate point of control, while that is not the case. So in someway this whole question may seem like a security issue.

**Comment by micahhausler** [comment]
The service account annotation ultimately isn't a trust boundary, it along with this webhook is a convenience for end users. Anyone is free to update their pod spec with the "proper" role ARN in an Env Var (and also add the volumes) as they see fit.

**Comment by errordeveloper** [comment]
> One way I can think of to trigger pod changes when the role annotation changes would be using a trick that Helm uses, where you have an annotation on your pod that is a hash of the IAM role.

That's a bit of a hack, and clearly only possible within Helm.

Actually, what if there was a way for user to set desired role as a pod annotation and leave service account without the role annotations? That would essentially allow tighter coupling of pod version to role desired for it.

> The service account annotation ultimately isn't a trust boundary, it along with this webhook is a convenience for end users.

Yes, but I think that's not particularly evident. To the user the annotation is the only visible point of control inside the Kubernetes API. In other words, with my Kubernetes glasses I don't really think of anything beyond the annotation. It's also possible that role definition is not controlled by the user, in which case the annotation is all they have to play with.

> Anyone is free to update their pod spec with the "proper" role ARN in an Env Var (and also add the volumes) as they see fit and bypass the webhook/annotation all together.

That sounds so much more laborious....

**Comment by errordeveloper** [comment]
One more point...

Say we have an application in a pod, it uses a service account that has a Kubernetes role binding and AWS IAM role. Changes to Kubernetes role will have immediate effect. Changes to IAM role/policy will also have immediate effect. However, that is not the case for changes to the IAM role annotation (say there is a new role, or role is reset in order to revoke any IAM permissions), which seems like a gap in the overall behaviour of the given APIs.

If IAM role was assigned to a pod by an annotation on the pod, it would be clear to the user what the relationship between IAM role assignment and the pod is tightly coupled to the lifecycle of the pod.

**Comment by micahhausler** [comment]
> Say we have an application in a pod, it uses a service account that has a Kubernetes role binding and AWS IAM role. Changes to Kubernetes role will have immediate effect. Changes to IAM role/policy will also have immediate effect. However, that is not the case for changes to the IAM role annotation (say there is a new role, or role is reset in order to revoke any IAM permissions), which seems like a gap in the overall behaviour of the given APIs.

I think the confusion is that _capability_ is mutable on pods (RBAC/IAM policy) but _identity_ is not (ServiceAccount/IAM role). For identity wouldn't you say though that a change to a pod's ServiceAccount also wouldn't have an immediate effect because the pod is immutable? You'd have to create a new pod to get the new Service Account. This comes 'for free' on a deployment because the deployment/replicaSet controllers manage the change for you

**Comment by micahhausler** [comment]
> If IAM role was assigned to a pod by an annotation on the pod, it would be clear to the user what the relationship between IAM role assignment and the pod is tightly coupled to the lifecycle of the pod.

We went back and forth initially on where to put the annotation, Pod or Service Account, and landed on SA because it enforces the idea that the ServiceAccount is the identity, and you most likely only want a ServiceAccount to assume a single IAM role.  

That being said, I'm open to adding support for a pod annotation specifying a role, but I'd want to see the docs (README or anywhere else) clearly call this out as less preferred. I think it is much more surprising (and worse) to have users annotate the pod and come to find out later that their pod can assume multiple roles beyond what it needs. I want to try to limit the scenarios where multiple users just use the 'default' service account for multiple IAM roles, not realizing that their pod could assume a different role.

**Comment by errordeveloper** [comment]
> You'd have to create a new pod to get the new Service Account. This comes 'for free' on a deployment because the deployment/replicaSet controllers manage the change for you.

Yes, but that's on the pod, hence I'm advocating for tying IAM roles to a pod also. In my mind that would result in closer alignment of the relevant aspects of AWS IAM API and the Kubernetes APIs. That would also imply that pod controllers help in the same way.

> We went back and forth initially on where to put the annotation, Pod or Service Account, and landed on SA because it enforces the idea that the ServiceAccount is the identity, and you most likely only want a ServiceAccount to assume a single IAM role.

I could totally imagine many lengthy internal conversations! The reasoning is very helpful to know, is it stated somewhere in the docs?

>  Think it is much more surprising (and worse) to have users annotate the pod and come to find out later that their pod can assume multiple roles (and thus have access to additional capabilities) beyond what it needs.

Once you said this, I realise that while suggesting the above,I was assuming that the IAM role definition would still refer to service account name. And if that'd be the case, the API would be really quite broken :)

**Comment by errordeveloper** [comment]
So here is a new idea: provide a way for users to observe and remedy inconsistencies, e.g.:


- there exists a service account that has pods which use it, suddenly it gets an IAM role assign to it (could be intentional, or by accident)
- a pod uses a service account and has `AWS_ROLE_ARN` environment variable set etc,  IAM role annotation on the service account get updated, and the pod in question no has the same role

In both of the cases the following would be very useful:
- user gets an alert (via their monitoring system of choice, or a governance/policy system)
- user has an option to either undo the change or terminate the pod (in some cases it could be automated)

**Comment by micahhausler** [comment]
> So here is a new idea: provide a way for users to observe and remedy inconsistencies, e.g.:

> * there exists a service account that has pods which use it, suddenly it gets an IAM role assigned to it (could be intentional, or by accident)
> * a pod uses a service account and has AWS_ROLE_ARN environment variable set etc, IAM role annotation on the service account get updated, and the pod in question no has the same role

> In both of the cases the following would be very useful:

> * user gets an alert (via their monitoring system of choice, or a governance/policy system)
> * user has an option to either undo the change or terminate the pod (in some cases it could be automated)

These sound like good options but I think they all are outside the scope of this webhook. Given that capability is mutable and identity is not on a given pod, is there anything you'd want to see changed in this webhook?

**Comment by errordeveloper** [comment]
> These sound like good options but I think they all are outside the scope of this webhook. Given that capability is mutable and identity is not on a given pod, is there anything you'd want to see changed in this webhook?

No, at the moment I don't think I can anything specific to suggest right now. As I said this was a question, and perhaps an open-ended one, it just seemed like this repo is most appropriate forum to have this discussion.

**Comment by micahhausler** [comment]
Glad to discuss, thanks! Closing with no issue

**Comment by mcanevet** [comment]
In case it interested someone, here is a Kyverno policy as a workaround:

```yaml
---
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: mutate-deployment-on-serviceaccount-update
spec:
  mutateExistingOnPolicyUpdate: false
  rules:
    - name: mutate-deployment-on-serviceaccount-update
      match:
        any:
          - resources:
              kinds:
                - ServiceAccount
              annotations:
                eks.amazonaws.com/role-arn: '*'
              operations:
                - UPDATE
      mutate:
        targets:
          - apiVersion: apps/v1
            kind: Deployment
            namespace: "{{request.namespace}}"
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  eks.amazonaws.com/role-arn: "{{request.object.metadata.annotations.\"eks.amazonaws.com/role-arn\"}}"
              spec:
                <(serviceAccountName): "{{ request.object.metadata.name }}"
```
Every time the `annotation` changes in the `ServiceAccount`, Kyverno patches the Pod template of each `Deployment` using this `ServiceAccount` which triggers a new version of the `ReplicaSet`.
