### ISSUE TITLE
Self Hosted Cluster: Nodes fail to join cluster after changes to master

### ISSUE THREAD

**Issue by sciffer** [aws/amazon-eks-pod-identity-webhook#29]
I'm not sure this is a bug, probably more of a question.
I have an existing self hosted Kops made cluster(ver 1.15.6) in AWS that I've been trying to migrate to use the pod identity solution. After setting up the keys, deploying the pod identity webhook to kubernetes(with the relevant pod and permissions) - non errors where shown on the pod at that stage.
I wen't a head and made the changes to the masters(api-audiences=sts.amazonaws.com, keys and issuer) and started the masters, once the masters started with the new settings:
kubectl get nodes - showed all the nodes as not ready without recovering.
At this stage I did not have any deployments/pods that were suppose to use the pod identity service, the masters seemed to recognize once each other properly and communicate properly - but the existing nodes were kept not ready and became invalid from the cluster perspective(masters). Looking at the logs, I could clearly see that masters could no longer authenticate with all the node components (permission denied), as if they are not compatible with the new authentication/authorization settings.
I was certain that this iam integration is an add-on only and should not invalidate/replace the builtin kubernetes authentication/authorization mechanism.
But, obviously I'm missing something basic here:
1. Does setting the api-audiences to sts.amazon.com overrides the kubernetes as a valid authentication/authorization provider? Or is it just an add-on, not clear from the documentation.
2. Am I missing something else? 
Will appreciate any assistance.

**Comment by micahhausler** [comment]
Are you trying to use the webhook to have the Kubernetes controller manager authenticate to AWS using the token flow?

>  After setting up the keys, deploying the pod identity webhook to kubernetes(with the relevant pod and permissions) - non errors where shown on the pod at that stage.

Which pod is not showing errors?

> I wen't a head and made the changes to the masters(api-audiences=sts.amazonaws.com, keys and issuer) and started the masters, once the masters started with the new settings:

I don't think this is what you want to do. Setting the `api-audiences` flag causes 2 behaviors:
* Projected volume tokens that don't specify an audience get their audience field set to the flag value
* Tokens containing the specified audience can be used to authenticate to the Kubernetes API server

See the [Audiences](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md#audiences) section of the self-hosted guide. That being said, I don't think this is the source of your issue.

What did you set the issuer to? Can you post what other flags you changed or added?

> Does setting the api-audiences to sts.amazon.com overrides the kubernetes as a valid authentication/authorization provider? Or is it just an add-on, not clear from the documentation.

No, this should be orthogonal for regular service account tokens

**Comment by sciffer** [comment]
1. I'm trying to assign certain pods/deeployments AWS IAM role, so that I could control on per pod/deployment permissions for AWS services(instead of providing those permissions to all the node instances of the cluster).
2. The pod that I'm referring to is the pod-identity-webhook pod that I have deployed in the cluster.
3. So, Audiences should be referring to the kubernetes api server service?
4. The flaggs that I used, were:
  kubeAPIServer:
    apiAudiences:
    - sts.amazonaws.com
    serviceAccountIssuer: https://XXXXXXXXX.s3.amazonaws.com
    serviceAccountKeyFile:
    - /etc/kubernetes/pki/kube-apiserver/secrets/oidc-issuer.pub
    serviceAccountSigningKeyFile: /etc/kubernetes/pki/kube-apiserver/secrets/oidc-issuer.key

It's the yaml format that kops accepts and verified that they got properly translated into kube-APIServer parameters on the master nodes.
Obviously XXXXXXX is the s3 bucket name that holds my key.json + .well-known/openid-configuration files.

**Comment by micahhausler** [comment]
Did you enable the `TokenRequest` Feature gate on the API server?

> Looking at the logs, I could clearly see that masters could no longer authenticate with all the node components (permission denied), as if they are not compatible with the new authentication/authorization settings.

Can you post the relevant log lines?

**Comment by sciffer** [comment]
1. None of the feature gates are enabled in my cluster.
2. The logs output currently is:
W0108 19:45:20.395442       1 client_config.go:551] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0108 19:45:21.756368       1 store.go:61] Fetched secret: kube-system/pod-identity-webhook
I0108 19:45:21.756757       1 main.go:173] Creating server
I0108 19:45:21.756998       1 main.go:193] Listening on :9999 for metrics and healthz
I0108 19:45:21.757007       1 main.go:187] Listening on :443

I did disable those features to reconnect the nodes to the masters, once I enabled the features - I got disconnected form the nodes, so kubectl could not see the actual pod or it's logs obviously.

**Comment by while1eq1** [comment]
@sciffer did you ever resolve this? if so how did you fix it?, Im currently running into this exact same issue.

**Comment by sciffer** [comment]
No, could not make it work, documentation on this project is really lacking
and I tried even scripts that someone wrote to set it up without success.
Due to time limitations decided to use zalando’s solution for the time
being, at least until this one will seem more mature with better
documentation.

**Comment by povils** [comment]
Same here. I couldn't make it working

**Comment by while1eq1** [comment]
can we reopen this issue please? as it is not resolved.

**Comment by povils** [comment]
Hey @while1eq1  and @sciffer , i think I got my nodes connecting by specifying the same private key as controller manager has. In My kops looks like that:
```yaml
  kubeAPIServer:
    serviceAccountKeyFile:
      - /srv/kubernetes/server.key
      - /srv/kubernetes/oidc-issuer.pub
    serviceAccountSigningKeyFile: /srv/kubernetes/oidc-issuer.key
    apiAudiences:
      - sts.amazonaws.com
    serviceAccountIssuer: https://s3-my_region.amazonaws.com/my_bucket
`

Can you try?

**Comment by while1eq1** [comment]
@povils Im testing now, I'll keep you updated. Also, out of curiosity, which method are you using to get your oidc-issuer.pub and oidc-issuer.key onto the nodes?

**Comment by povils** [comment]
@while1eq1 I made it work completely. Currently I just use user_data to fetch these keys from s3 bucket. In kops you can do something like
```yaml
  additionalUserData:
    - name: download-oidc-keys.sh
      type: text/x-shellscript
      content: |
        #!/bin/sh
        aws s3 cp s3://my_bucket/oidc-issuer.key /srv/kubernetes/oidc-issuer.key
        aws s3 cp s3://my_bucket/oidc-issuer.pub /srv/kubernetes/oidc-issuer.pub
```

**Comment by while1eq1** [comment]
@povils , kops config:
`  kubeAPIServer:
    serviceAccountKeyFile:
      - /etc/kubernetes/pki/kube-apiserver/oidc-issuer.pub
      - /srv/kubernetes/server.key
    serviceAccountSigningKeyFile: /etc/kubernetes/pki/kube-apiserver/oidc-issuer.key
    apiAudiences:
      - sts.amazonaws.com
    serviceAccountIssuer: https://s3.us-east-1.amazonaws.com/xxx`

kube-controller-manager is doing this:
`E0120 15:43:35.956835       1 cidr_allocator.go:124] Failed to list all nodes: Unauthorized`

kube-api-server is doing this:
`E0120 15:43:35.956546       1 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, square/go-jose: error in cryptographic primitive]`

**Comment by while1eq1** [comment]
which means all nodes are currently "NotReady"

**Comment by while1eq1** [comment]
kube-api-server still getting the following:
```
E0120 22:17:40.393234       1 leaderelection.go:324] error retrieving resource lock kube-system/kube-controller-manager: endpoints "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "endpoints" in API group "" in the namespace "kube-system"
```

**Comment by while1eq1** [comment]
ok so I got it finally, so for me it was a combo of 2 things that were wrong.

1. my s3 bucket wasn't "completely public", the objects were but "list" wasnt allowed at the bucket level
2. I had to add `- /srv/kubernetes/server.key` to `serviceAccountKeyFile:`, Thank You @povils  for your help today.

This issue can remain closed, hope it helps others who were struggling with this

**Comment by sciffer** [comment]
Yeah, my guess is that I missed adding the server.key to the
serviceAccountKeyFile. That's what caused the master to fail authentication
with the nodes.
It was obvious that based on the guides, something is missing in order to
retain the built-in cluster authentication.

**Comment by bjethwan** [comment]
I ran into the same issue when playing with this project on  KIND k8s cluster.
https://github.com/kubernetes-sigs/kind/issues/1839
