### ISSUE TITLE
Please create a release/tag

### ISSUE THREAD

**Issue by max-rocket-internet** [aws/amazon-eks-pod-identity-webhook#31]
It seems AWS [aren't going to publish any docker images](https://github.com/aws/amazon-eks-pod-identity-webhook/issues/5) for this tool so it would at least be good to have a release or tag created that we can use as a reference when building our own docker images 🙂

**Comment by micahhausler** [comment]
Done :) 

* [v0.2.0](https://github.com/aws/amazon-eks-pod-identity-webhook/releases/tag/v0.2.0)
* [v0.1.0](https://github.com/aws/amazon-eks-pod-identity-webhook/releases/tag/v0.1.0)
