### ISSUE TITLE
TLS handshake error from 10.0.77.120:45664: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by max-rocket-internet** [aws/amazon-eks-pod-identity-webhook#33]
**What happened**:

Built docker container from master and then Install everything from scratch and this is the pod logs:

```
W0123 14:25:32.328734       1 client_config.go:551] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0123 14:25:32.352056       1 store.go:61] Fetched secret: kube-system/pod-identity-webhook
I0123 14:25:32.362180       1 main.go:172] Creating server
I0123 14:25:32.362398       1 main.go:192] Listening on :9999 for metrics and healthz
I0123 14:25:32.362417       1 main.go:186] Listening on :443
2020/01/23 14:25:49 http: TLS handshake error from 10.0.77.120:45664: remote error: tls: bad certificate
2020/01/23 14:26:09 http: TLS handshake error from 10.0.77.120:46086: remote error: tls: bad certificate
2020/01/23 14:26:29 http: TLS handshake error from 10.0.77.120:46532: remote error: tls: bad certificate
```

**What you expected to happen**:

No errors

**How to reproduce it (as minimally and precisely as possible)**:

Just run `make cluster-up IMAGE=xxx`.

**Anything else we need to know?**:

**Environment**:

- AWS Region: eu-west-1
- EKS Platform version: `eks.6`
- Kubernetes version: `1.14`
- Webhook Version: `master`

**Comment by max-rocket-internet** [comment]
OK so I think I've misunderstood and we don't actually need to run the deployment *when using EKS*, as it's already included as part of the service.

We only need to create an OIDC provider, annotate the `ServiceAccount` and create an IAM role with the correct trust policy.

**Comment by Swalloow** [comment]
This issue occurs when using SELF_HOSTED_SETUP.
The image build worked fine and I deployed it through a Makefile.
`make cluster-up IMAGE=xxx`

Environment:
- Kubernetes version: 1.15
- Webhook version: master

**Comment by f-ld** [comment]
I tried this project on our kops (i.e. self hosted) cluster trying to understand how to deploy it and got similar error:
```
2020/08/14 12:36:13 http: TLS handshake error from 100.96.0.1:26429: remote error: tls: bad certificate
```
in that case the CA bundle was not correct (I used a certificate from another test cluster than the one I was testing on). IT has to be a base64 encoded PEM certificate (so base64 encoding of a multine content starting with `-----BEGIN CERTIFICATE-----` and ending with `-----END CERTIFICATE-----`).

Fixing it help go one step further:
```
I0814 14:01:27.526970       1 cache.go:51] Fetching sa <namespace>/<service-account> from cache
I0814 14:01:27.547390       1 middleware.go:132] path=/mutate method=POST status=200 user_agent=kube-apiserver-admission body_bytes=1417
```

**Comment by kdalporto** [comment]
@f-ld 
Reviving an old thread as I'm running into this same issue. When you were using the wrong CA_Bundle, was that what the [webhook-patch-ca-bundle.sh](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/hack/webhook-patch-ca-bundle.sh) gave you? 

I get the same error but it's using the default CA bundle of my cluster.
