### ISSUE TITLE
[Question] Auto scaling with IRSA enabled - is this supported for self-hosted?

### ISSUE THREAD

**Issue by johnmccabe** [aws/amazon-eks-pod-identity-webhook#42]
Hi,
For a kops deployed cluster with IRSA enabled is there any recommendation on how to address auto-scaling. I'm seeing the node auto scaling group successfully provision a new instance, but it subsequently fails to join the cluster, I assume due to the node role only have assumeRole permissions.

Are you aware of any workarounds/activity around this on the kops/IRSA sides?
Thanks,
John

**Comment by micahhausler** [comment]
> For a kops deployed cluster with IRSA enabled is there any recommendation on how to address auto-scaling. I'm seeing the node auto scaling group successfully provision a new instance, but it subsequently fails to join the cluster,

I don't think that IRSA is related because the webhook and auth flow only operates on pod creation.

How are you doing node authentication? 

>  I assume due to the node role only have assumeRole permissions.

What role does your node assume? Are you trying to pull any ECR images? Did you grant ECR pull permissions?

**Comment by johnmccabe** [comment]
> How are you doing node authentication?

I'm not clear on what the "node authentication" is you're referring to in this context, could you clarify?

> 
> > I assume due to the node role only have assumeRole permissions.
> 
> What role does your node assume? Are you trying to pull any ECR images? Did you grant ECR pull permissions?

Kops initially creates a node role with EC2 list, S3 list and ECR read (needed for its `nodeup` utility to complete cluster node bootstrapping). After cluster creation has completed I've dropped those permissions and the node role just has `sts:AssumeRole` with the OIDC trust relationship. This works just as expected with the webhook and pods.

Now when the EC2 autoscaler starts a new cluster node in a node group, it uses the same node role as above, which now only has `sts:AssumeRole`. The `nodeup` tool still needs access to the EC2/S3/ECR resources, but since the node role is now reduced this fails. I assume I'll have to update `nodeup` to use AssumeRoleWithWebIdentity and somehow generate a signed JWT to assume a new role with the same permissions as the original node role - this would be happening outside of the cluster, not via the webhook. It's this last part I'm not clear on, whether there may be some alternative I'm not aware of (very likely).

Thanks for providing feedback, hopefully this is a bit clearer.

**Comment by micahhausler** [comment]
> Kops initially creates a node role with EC2 list, S3 list and ECR read (needed for its nodeup utility to complete cluster node bootstrapping). After cluster creation has completed I've dropped those permissions and the node role just has sts:AssumeRole with the OIDC trust relationship. This works just as expected with the webhook and pods.

Ah right so, kops _requires_ that S3 permission so that nodes can get the cluster CA and other certificates. I think that is the source of your problem. The node role will still need those permissions you removed for new nodes to join.

When you say 

> the node role just has sts:AssumeRole with the OIDC trust relationship. This works just as expected with the webhook and pods.

is the `AssumeRole` permission in the _trust policy_ or the `role policy`?

> Now when the EC2 autoscaler starts a new cluster node in a node group, it uses the same node role as above, which now only has sts:AssumeRole.

The "it uses" part, is that the autoscaler using _itself_? Or the role _it assigns_ to new nodes in the ASG?

> I assume I'll have to update nodeup to use AssumeRoleWithWebIdentity and somehow generate a signed JWT to assume a new role with the same permissions as the original node role - this would be happening outside of the cluster, not via the webhook. It's this last part I'm not clear on, whether there may be some alternative I'm not aware of (very likely).

JWTs for pods are created by the kube-api server (POST `/api/v1/namespaces/<namespace>/serviceaccounts/<service account>/token`) by the kubelet. The Kubelet will always be the root of trust for pods, and you'll need a way for the kubelet to authenticate to the cluster. Since you're using Kops, that is S3.

You'll need to re-enable the default IAM permissions on the node role for kops
