### ISSUE TITLE
admission webhook "iam-for-pods.amazonaws.com" does not support dry run

### ISSUE THREAD

**Issue by dliao-tyro** [aws/amazon-eks-pod-identity-webhook#46]
**What happened**:
Executing `kubectl diff` against a deployment using IAM roles for service accounts (IRSA) resulted in the error "Error from server (BadRequest): admission webhook "iam-for-pods.amazonaws.com" does not support dry run".

It would be nice to support this feature so it is part of our workflow.

**What you expected to happen**:
Expected to see the diff
**How to reproduce it (as minimally and precisely as possible)**:
kubectl diff targeting an EKS cluster.
**Anything else we need to know?**:

**Environment**:
- AWS Region: ap-southeast-2
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.1
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`): 1.15
- Webhook Version:

**Comment by aweis89** [comment]
We've been seeing this issue when working with Pods directly, Deployments, StatefulSets and Jobs seem to work though

**Comment by dliao-tyro** [comment]
Yes, can also confirm that deployments, statefulsets and jobs are working now

**Comment by anshulsri12** [comment]
So how to resolve for Pods? Not use it?

**Comment by AndrewFarley** [comment]
Yes, what is the actual fix for this please?

**Comment by danopia** [comment]
Applying the change in https://github.com/aws/amazon-eks-pod-identity-webhook/pull/79 should let Kubernetes know how to dry-run with this webhook. Are you still seeing an error dryrunning after that change?

**Comment by migueleliasweb** [comment]
I can confirm the error still occurs for `Pods`. All other `Kinds` seem fine.

The erro message I'm getting is:

```
Error from server (BadRequest): error when creating "STDIN": admission webhook "iam-for-pods.amazonaws.com" 
does not support dry run
```

**Comment by danopia** [comment]
Patching sideEffects: None onto into the mutating webhook configuration is the effective fix. Sounds like EKS still isn't doing that by default? I'm on GKE so i had to install the webhook myself.

**Comment by afirth** [comment]
This is still an issue on my EKS clusters, now upgraded to 1.23. Why isn't this webhook kept up to date by EKS (#79 is not present)?
Should I manually manage this or am I missing some line in the upgrade notes long ago?
