### ISSUE TITLE
Allow for wildcard of the namespace in the IAM condition

### ISSUE THREAD

**Issue by timduhenchanter** [aws/amazon-eks-pod-identity-webhook#58]
**What would you like to be added**:
Allow for the namespace to accept wildcards in the IAM statement condition block

**Why is this needed**:
To support ephemeral environments mounting back to a uniform IAM role

Our ephemeral environment generates a unique namespace with a prefix and UID on deploy but to access cross-account resources that have been granted privileges to a fixed role we need to be able to annotate the ServiceAccount with that fixed role across our ephemeral namespaces

**Comment by micahhausler** [comment]
Does something like the following not work for you?

```json
{
 "Version": "2012-10-17",
 "Statement": [
  {
   "Effect": "Allow",
   "Principal": {
    "Federated": "arn:aws:iam::111122223333:oidc-provider/oidc.us-west-2.eks.amazonaws.com/CLUSTER_ID"
   },
   "Action": "sts:AssumeRoleWithWebIdentity",
   "Condition": {
    "__doc_comment": "scope the role to any ",
    "StringLike": {
     "oidc.us-west-2.eks.amazonaws.com/CLUSTER_ID:sub": "system:serviceaccount:*:my-serviceaccount"
    }
   }
  }
 ]
}
```

**Comment by timduhenchanter** [comment]
User error.  I had this configured as demonstrated and was receiving validation issues but this was not the root cause.  Thanks for the response!
