### ISSUE TITLE
re-invoking webhook exits early

### ISSUE THREAD

**Issue by yangkev** [aws/amazon-eks-pod-identity-webhook#61]
**What happened**:
If the webhook is re-invoked (per [reinvocationPolicy: IfNeeded](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy)), the 2nd invocation exits without injecting any of the environment variables / volume mounts.

E.g., say you have mutating webhook `foo-webhook` which adds some sidecar containers, deployed along-side the `pod-identity-webhook` in a cluster.

Consider the following admission webhook execution scenario when admitting a `Pod` with a container, `containerA`.

1. `pod-identity-webhook` runs, modifies `containerA`
2. `foo-webhook` runs, adds `containerB`, `containerC`
3. `pod-identity-webhook` runs, and [does nothing, since a `volume` field is already present](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/4286d35c28724afa8059857a3fd9387e5c8d61ce/pkg/handler/handler.go#L177-L182)

Now `containerB` and `containerC` do not get environment variables / volume mounts added.

**What you expected to happen**:
I expect on re-invoking the `pod-identity-webhook` that it will continue to inject the service account token volume mount and environment variables on new containers.

**How to reproduce it (as minimally and precisely as possible)**:
This test case for [`TestEnvUpdate`](https://github.com/aws/amazon-eks-pod-identity-webhook/blob/4286d35c28724afa8059857a3fd9387e5c8d61ce/pkg/handler/handler_test.go#L411-L457)
```
{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
	"name": "balajilovesoreos",
	"uid": "be8695c4-4ad0-4038-8786-c508853aa255"
  },
  "spec": {
	"containers": [
	  {
		"image": "amazonlinux",
		"name": "balajilovesoreos",
	  }
	],
	"serviceAccountName": "default",
	"volumes": [
	  {
	    "name": "aws-iam-token"
	  }
	]
  }
}
```

Expected Patch:
```
[
    {
        "op": "add",
        "path": "/spec/containers",
        "value": [
            {
                "env": [
                    {
                        "name": "AWS_ROLE_ARN",
                        "value": "arn:aws:iam::111122223333:role/s3-reader"
                    },
                    {
                        "name": "AWS_WEB_IDENTITY_TOKEN_FILE",
                        "value": "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
                    },
                    {
                        "name": "AWS_DEFAULT_REGION",
                        "value": "seattle"
                    },
                    {
                        "name": "AWS_REGION",
                        "value": "seattle"
                    }
                ],
                "image": "amazonlinux",
                "name": "balajilovesoreos",
                "resources": {},
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/eks.amazonaws.com/serviceaccount",
                        "name": "aws-iam-token",
                        "readOnly": true
                    }
                ]
            }
        ]
    }
]
```

Actual Patch:
```
null
```

**Anything else we need to know?**:

**Environment**:
- AWS Region:
- EKS Platform version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.platformVersion`):
- Kubernetes version (if using EKS, run `aws eks describe-cluster --name <name> --query cluster.version`):
- Webhook Version:

**Comment by jqmichael** [comment]
> pod-identity-webhook runs, and does nothing, since a volume field is already present
Err, that's a bummer. 

It should exit for that container not the entire pod.
