### ISSUE TITLE
EKS 1.16 missing pod-identity-webhook

### ISSUE THREAD

**Issue by edbighead** [aws/amazon-eks-pod-identity-webhook#68]
**What happened**:
After upgrading from EKS 1.15 to EKS 1.16,  podsare missing the following env vars:
```
AWS_ROLE_ARN=arn:aws:iam::xxx:role/oidc-my-service-api-qa
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```
Found that pod-identity-webhook (which is responsible of injecting those) is missing in 1.16. It's still present on our 1.15 clusters.

**EKS 1.15**
```
kubectl get mutatingwebhookconfigurations pod-identity-webhook
NAME                   CREATED AT
pod-identity-webhook   2020-01-11T17:01:52Z
```

**EKS 1.16**
```
kubectl get mutatingwebhookconfigurations pod-identity-webhook
Error from server (NotFound): mutatingwebhookconfigurations.admissionregistration.k8s.io "pod-identity-webhook" not found
```
**What you expected to happen**:
pod-identity-webhook  to be present after upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade EKS 1.15 to 1.16 and execute `kubectl get mutatingwebhookconfigurations pod-identity-webhook`

**Environment**:
- AWS Region: ap-southeast-1
- EKS Platform version: "eks.2"
- Kubernetes version: "1.16"
- Webhook Version: -

**Comment by edbighead** [comment]
To fix this, I built and pushed the image to my ECR repo, then re-install it with `make cluster-up`.

**Comment by amitkarpe** [comment]
Hi @edbighead,

How to recreate `mutatingwebhookconfigurations pod-identity-webhook`?
Where I can find its manifest file?

**Comment by edbighead** [comment]
> Hi @edbighead,
> 
> How to recreate `mutatingwebhookconfigurations pod-identity-webhook`?
> Where I can find its manifest file?

clone the repo and run the make command i mentioned above, manifests can be found here https://github.com/aws/amazon-eks-pod-identity-webhook/tree/master/deploy

**Comment by jqmichael** [comment]
Hey @edbighead and @amitkarpe, do you mind ping us on [Slack](https://app.slack.com/client/T09NY5SBT/C8SH2GSL9/) with the cluster ARN and timeframe so that we can look into on our side?

**Comment by amitkarpe** [comment]
Hi @jqmichael,
I was not able to connect to [this](https://app.slack.com/client/T09NY5SBT/C8SH2GSL9/) slack channel. Which slack channel it is?
I am already a member of kubernetes/EKS channel. You can ping me there: https://kubernetes.slack.com/archives/C8SH2GSL9
