### ISSUE TITLE
SELF_HOSTED_SETUP: How to use the same iam idp for multiple k8s cluster?

### ISSUE THREAD

**Issue by bjethwan** [aws/amazon-eks-pod-identity-webhook#72]
https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/SELF_HOSTED_SETUP.md 

Is there a way I can use the same S3 bucket with different sets of PKI key pairs for each k8s cluster running on aws?
Can we use the same keys.json and .well-known/openid-configuration with multiple keys (each with different kid may)?

Environment
A number of self-hosted k8s in aws.
AWS Region: us-west-2
Kubernetes version: 1.17.11 onwards

**Comment by micahhausler** [comment]
Multiple keys are supported by the OIDC spec, but should only be used for rotating the signing key of an issuer. Using the same IDP for multiple clusters is strongly discouraged. It obscures the identity that is assuming a role (you won't be able to differentiate which cluster the request came from), even if you use separate keys and advertise both keys in the same issuer. If you used the same key in both clusters, you're in an even worse situation, where tokens from one cluster could be used against another
