### ISSUE TITLE
Support cert-manager based deployments 

### ISSUE THREAD

**Issue by mcristina422** [aws/amazon-eks-pod-identity-webhook#94]
**What would you like to be added**: 

Enable cert-manager enabled clusters to use this webhook 

This request is to support webhook certificates via a https://github.com/jetstack/cert-manager ca injector. This will benefit the webhook in a few ways, the certificate will no longer need to be generated by the application itself, removing a dependency on the CSR based upstream k8s certificate manager (where issues do arise like the metrics changes in https://github.com/aws/amazon-eks-pod-identity-webhook/pull/92). Additionally, it will remove the need for secret and CSR RBAC, as cert-manager will [inject the CA](https://cert-manager.io/docs/concepts/ca-injector/) to the webhook at deploy time. The certificate will get rotated in place when it expires

**Why is this needed**:
The "standard" set by kubebuilder/controller-runtime is cert manager based certificates as it simplifies certificate management 
https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html#deploying-the-cert-manager

Both cert-manager based webhooks and CSR webhooks can both be supported at the same time with feature flags and updated RBAC. We run this today internally by updating RBAC, creating a cert-manager.io Certificate, setting the cert-manager.io/inject-ca-from annotation on the webhook, disabling the in cluster flag, and manually setting tls-cert and tls-key to be a mounted secret volume. But I think the server needs to reload the certificate, like in https://github.com/kubernetes-sigs/controller-runtime/pull/421/files or else when the cert expires, the server will still use the certificate it loaded at startup, not the live certificate on the filesystem 

EDIT: The certwatcher may get exported in https://github.com/kubernetes-sigs/controller-runtime/issues/1292

**Comment by avdhoot** [comment]
@mcristina422 Can you please share steps how did it?

**Comment by avdhoot** [comment]
Thanks @mcristina422 for hints. Below yaml for how you can deploy `amazon-eks-pod-identity-webhook` with cert-manager
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-identity-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-identity-webhook
  template:
    metadata:
      labels:
        app: pod-identity-webhook
    spec:
      serviceAccountName: pod-identity-webhook
      containers:
        - name: pod-identity-webhook
          image: amazon/amazon-eks-pod-identity-webhook:2c44edc
          imagePullPolicy: Always
          command:
            - /webhook
            - --in-cluster=false
            - --namespace=kube-system
            - --service-name=pod-identity-webhook
            - --annotation-prefix=eks.amazonaws.com
            - --token-audience=sts.amazonaws.com
            - --logtostderr
          volumeMounts:
            - name: cert
              mountPath: "/etc/webhook/certs"
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: pod-identity-webhook-cert
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: pod-identity-webhook
  namespace: kube-system
spec:
  secretName: pod-identity-webhook-cert
  commonName: "pod-identity-webhook.kube-system.svc"
  dnsNames:
  - "pod-identity-webhook"
  - "pod-identity-webhook.kube-system"
  - "pod-identity-webhook.kube-system.svc"
  - "pod-identity-webhook.kube-system.svc.local"
  isCA: true
  duration: 43800h
  renewBefore: 8760h
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-identity-webhook
  namespace: kube-system
  annotations:
    cert-manager.io/inject-ca-from: kube-system/pod-identity-webhook
webhooks:
  - name: pod-identity-webhook.amazonaws.com
    failurePolicy: Ignore
    clientConfig:
      service:
        name: pod-identity-webhook
        namespace: kube-system
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]

**Comment by christopherhein** [comment]
In case you are interested in reviewing the implementation - https://github.com/kubernetes-sigs/controller-runtime/pull/1441 hopefully this fulfils your needs as well.

**Comment by patjones** [comment]
Wanted to bump this issue as well thank @mcristina422 and @avdhoot for the cert-manager integration above! I wanted to ask in mean the time how people are getting around the issue of the cert being loaded on start-up? Deleting the webhook pod with a job periodically? I see the above configuration is setting a long duration for the cert.

**Comment by mcristina422** [comment]
On our clusters we use a shorter duration cert and we automatically terminate our EKS nodes weekly, so pods will get rolled out frequently enough to get new certificates. A job to rollout the deployment makes sense to me! 

Long term the plan should be to refactor this webhook to use [this](https://github.com/kubernetes-sigs/controller-runtime/pull/1441) package to automatically reload the certificate

**Comment by avdhoot** [comment]
Long duration for the cert is short term fix for cert rotation issue If the
app does not reload when cert change.

**Comment by danopia** [comment]
This unrelated PR might help with the renewal story? https://github.com/aws/amazon-eks-pod-identity-webhook/pull/87

> This change adds support for the `--external-tls-renewal` flag which will make the k8s Secret "readonly", i.e only read but never update it. Instead of having the k8s go-client `certificate_manager.Manager` renew it via CSR API, it will just try to re-read it from the secret when it is is nearing expiration time.
