### ISSUE TITLE
Pod prioritization and how to keep it safe

### ISSUE THREAD

**Issue by 7echno** [aws/amazon-eks-pod-identity-webhook#99]
HI,

Our self hosted irsa setup is using 'amazon-eks-pod-identity-webhook' pod and I was wondering how to make it safe from eviction, but also to make it scheduled as prioritized pod.
We are considering to  add and use " `priorityClassName: system-node-critical` " in our deployment manifest.
We catch an issue on our test k8s cluster when single worker node  was terminated, we think that some pods were scheduled before webhook, and token was not mapped/injected into pods..

Do you have some suggestion, maybe some better approach how to make this pod safe ? 
 
Thank you,

**Comment by micahhausler** [comment]
Priority class is a good start, and if you want higher availability in general, I'd suggest running multiple replicas and enabling a [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) (specifically `.spec.minAvailable`)

**Comment by micahhausler** [comment]
Closing with no response
